#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use TroisOlen\PhpunitTp\Command\AnswerMediaRiddleCommand;

// Used components
// * Factory
$quoteRiddleFactory = new TroisOlen\PhpunitTp\Factory\QuoteRiddleFactory();

// Console application
$myConsoleApp = new Application(name: 'PHPUnit TP', version: '1.0.0');

$myConsoleApp
    ->add(new AnswerMediaRiddleCommand(quoteRiddleFactory: $quoteRiddleFactory));

$myConsoleApp->run();
