#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

// Used components
// * Factory
$quoteRiddleFactory = new TroisOlen\PhpunitTp\Factory\QuoteRiddleFactory();
// * Service
$quoteAnswerChecker = new TroisOlen\PhpunitTp\Service\QuoteAnswerChecker();

// Console application
$myConsoleApp = new Application(name: 'PHPUnit TP', version: '1.0.0');

$myConsoleApp
    ->add(
            new TroisOlen\PhpunitTp\Command\AnswerMediaRiddleCommand(
                quoteAnswerChecker: $quoteAnswerChecker,
                quoteRiddleFactory: $quoteRiddleFactory
            )
    );

$myConsoleApp->run();
